name: wck_vault
description: Waterproofing & Construction Knowledge Vault - Created by Noyon
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  file_picker: ^8.1.2
  pdfx: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/knowledge_base.json
    - assets/pdf_import_manifest.json
    - assets/source_pdfs/
